import { createFileRoute, Link, useRouter } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { AppShell } from "@/components/AppShell";
import { supabase } from "@/lib/supabase";
import { isAuthed } from "@/lib/auth-store";
import { Button } from "@/components/ui/button";
import { downloadTransferReceipt } from "@/lib/pdf-utils";
import {
  ArrowLeft,
  CheckCircle2,
  Download,
  FileText,
  Landmark,
  User,
} from "lucide-react";

export const Route = createFileRoute("/receipt/$id")({
  component: ReceiptPage,
});

type Receipt = {
  id: string;
  sender_id: string;
  amount: number;
  status: string;
  recipient_name?: string | null;
  recipient_account_number?: string | null;
  recipient_bank_name?: string | null;
  recipient_country?: string | null;
  recipient_currency?: string | null;
  reference?: string | null;
  receipt_number?: string | null;
  description?: string | null;
  transfer_fee?: number | null;
  created_at: string;
  completed_at?: string | null;
  profiles?: {
    full_name?: string | null;
    email?: string | null;
    account_number?: string | null;
  } | null;
};

function formatCurrency(value: number, currency = "USD") {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency,
  }).format(Number(value || 0));
}

function ReceiptPage() {
  const router = useRouter();
  const { id } = Route.useParams();

  const [receipt, setReceipt] = useState<Receipt | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadReceipt();
  }, [id]);

  async function loadReceipt() {
    const loggedIn = await isAuthed();

    if (!loggedIn) {
      router.navigate({ to: "/" });
      return;
    }

    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      router.navigate({ to: "/" });
      return;
    }

    const { data, error } = await supabase
      .from("transactions")
      .select(
        `
        *,
        profiles:sender_id (
          full_name,
          email,
          account_number
        )
      `
      )
      .eq("id", id)
      .eq("sender_id", user.id)
      .single();

    if (error) {
      alert(error.message);
      router.navigate({ to: "/transactions" });
      return;
    }

    setReceipt(data);
    setLoading(false);
  }

  function downloadPDF() {
    if (!receipt) return;

    const currency = receipt.recipient_currency || "USD";

    downloadTransferReceipt({
      receiptNumber: receipt.receipt_number || receipt.id,
      reference: receipt.reference || "-",
      senderName: receipt.profiles?.full_name || "Customer",
      recipientName: receipt.recipient_name || "Recipient",
      recipientBank: receipt.recipient_bank_name || "Bank",
      recipientAccount: receipt.recipient_account_number || "-",
      amount: formatCurrency(Number(receipt.amount || 0), currency),
      fee: formatCurrency(Number(receipt.transfer_fee || 0), currency),
      status: receipt.status || "completed",
      date: new Date(
        receipt.completed_at || receipt.created_at
      ).toLocaleString(),
    });
  }

  if (loading) {
    return (
      <AppShell>
        <div className="min-h-[70vh] grid place-items-center">
          <p className="text-sm text-muted-foreground">
            Loading receipt...
          </p>
        </div>
      </AppShell>
    );
  }

  if (!receipt) return null;

  const currency = receipt.recipient_currency || "USD";

  const isCompleted = ["completed", "successful"].includes(
    String(receipt.status || "").toLowerCase()
  );

  return (
    <AppShell>
      <div className="mx-auto max-w-4xl px-4 sm:px-6 py-8 space-y-6 animate-fade-in">
        <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <div className="flex items-center gap-2 text-gold">
              <FileText className="h-5 w-5" />
              Transfer Receipt
            </div>

            <h1 className="mt-2 font-display text-3xl font-semibold">
              Receipt Details
            </h1>

            <p className="mt-1 text-sm text-muted-foreground">
              Official transaction receipt generated by Atlas Capital Bank.
            </p>
          </div>

          <div className="flex gap-2">
            <Link to="/transactions" from="/">
              <Button variant="outline">
                <ArrowLeft className="h-4 w-4 mr-2" />
                Back
              </Button>
            </Link>

            <Button onClick={downloadPDF} disabled={!isCompleted}>
              <Download className="h-4 w-4 mr-2" />
              Download PDF
            </Button>
          </div>
        </div>

        {!isCompleted && (
          <div className="rounded-2xl border border-gold/30 bg-gold/10 p-4 text-sm text-muted-foreground">
            This receipt will be available after the transfer is completed.
          </div>
        )}

        <section className="relative overflow-hidden rounded-3xl border border-border bg-gradient-to-br from-card via-card to-secondary/40 p-6 sm:p-8">
          <div className="absolute -right-24 -top-24 h-72 w-72 rounded-full bg-gold/10 blur-3xl" />

          <div className="relative flex flex-col gap-6 sm:flex-row sm:items-start sm:justify-between">
            <div>
              <p className="text-xs uppercase tracking-wider text-muted-foreground">
                Receipt Number
              </p>

              <h2 className="mt-2 font-display text-2xl font-semibold">
                {receipt.receipt_number || receipt.id}
              </h2>

              <p className="mt-2 text-sm text-muted-foreground">
                Reference: {receipt.reference || "-"}
              </p>
            </div>

            <div className="rounded-2xl border border-border bg-background/70 p-5 min-w-[240px]">
              <p className="text-xs uppercase tracking-wider text-muted-foreground">
                Amount
              </p>

              <h3 className="mt-2 font-display text-3xl font-semibold">
                {formatCurrency(Number(receipt.amount || 0), currency)}
              </h3>

              <span
                className={`mt-3 inline-flex rounded-full px-3 py-1 text-xs capitalize ${
                  isCompleted
                    ? "bg-success/15 text-success"
                    : "bg-gold/15 text-gold"
                }`}
              >
                {receipt.status}
              </span>
            </div>
          </div>
        </section>

        <section className="grid gap-4 md:grid-cols-2">
          <InfoCard
            icon={User}
            title="Sender"
            rows={[
              ["Name", receipt.profiles?.full_name || "-"],
              ["Email", receipt.profiles?.email || "-"],
              ["Account", receipt.profiles?.account_number || "-"],
            ]}
          />

          <InfoCard
            icon={Landmark}
            title="Recipient"
            rows={[
              ["Name", receipt.recipient_name || "-"],
              ["Bank", receipt.recipient_bank_name || "-"],
              ["Account", receipt.recipient_account_number || "-"],
              ["Country", receipt.recipient_country || "-"],
            ]}
          />
        </section>

        <section className="card-surface p-6">
          <h2 className="font-display text-xl font-semibold mb-5">
            Transaction Summary
          </h2>

          <div className="grid gap-3 sm:grid-cols-2">
            <Summary label="Description" value={receipt.description || "-"} />
            <Summary
              label="Transfer Fee"
              value={formatCurrency(Number(receipt.transfer_fee || 0), currency)}
            />
            <Summary
              label="Created"
              value={new Date(receipt.created_at).toLocaleString()}
            />
            <Summary
              label="Completed"
              value={
                receipt.completed_at
                  ? new Date(receipt.completed_at).toLocaleString()
                  : "-"
              }
            />
          </div>
        </section>

        <section className="rounded-2xl border border-success/30 bg-success/10 p-5">
          <div className="flex gap-3">
            <CheckCircle2 className="h-5 w-5 text-success shrink-0" />
            <div>
              <p className="font-semibold">Secure Receipt</p>
              <p className="mt-1 text-sm text-muted-foreground">
                This electronic receipt was generated by Atlas Capital Bank and
                can be used as proof of completed transfer once the status is
                completed.
              </p>
            </div>
          </div>
        </section>
      </div>
    </AppShell>
  );
}

function InfoCard({
  icon: Icon,
  title,
  rows,
}: {
  icon: React.ComponentType<{ className?: string }>;
  title: string;
  rows: [string, string][];
}) {
  return (
    <div className="card-surface p-6">
      <div className="flex items-center gap-2 mb-5">
        <Icon className="h-5 w-5 text-gold" />
        <h2 className="font-display text-xl font-semibold">{title}</h2>
      </div>

      <div className="space-y-3">
        {rows.map(([label, value]) => (
          <div
            key={label}
            className="flex items-center justify-between gap-4 border-b border-border/60 pb-2 text-sm"
          >
            <span className="text-muted-foreground">{label}</span>
            <span className="font-medium text-right break-all">{value}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

function Summary({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-xl border border-border bg-secondary/30 p-4">
      <p className="text-xs uppercase tracking-wider text-muted-foreground">
        {label}
      </p>
      <p className="mt-2 font-medium">{value}</p>
    </div>
  );
}