/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as TransferRouteImport } from './routes/transfer'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TransferStatusIdRouteImport } from './routes/transfer-status/$id'
import { Route as ReceiptIdRouteImport } from './routes/receipt.$id'
import { Route as AdminTransfersRouteImport } from './routes/admin/transfers'
import { Route as AdminSecurityRouteImport } from './routes/admin/security'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminKycRouteImport } from './routes/admin/kyc'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminCardsRouteImport } from './routes/admin/cards'
import { Route as AdminBeneficiariesRouteImport } from './routes/admin/beneficiaries'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminActivityRouteImport } from './routes/admin/activity'

const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TransferStatusIdRoute = TransferStatusIdRouteImport.update({
  id: '/transfer-status/$id',
  path: '/transfer-status/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptIdRoute = ReceiptIdRouteImport.update({
  id: '/receipt/$id',
  path: '/receipt/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransfersRoute = AdminTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCardsRoute = AdminCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBeneficiariesRoute = AdminBeneficiariesRouteImport.update({
  id: '/beneficiaries',
  path: '/beneficiaries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/cards': typeof CardsRoute
  '/dashboard': typeof DashboardRoute
  '/notifications': typeof NotificationsRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/transfer': typeof TransferRoute
  '/verification': typeof VerificationRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/beneficiaries': typeof AdminBeneficiariesRoute
  '/admin/cards': typeof AdminCardsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/transfers': typeof AdminTransfersRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/transfer-status/$id': typeof TransferStatusIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/cards': typeof CardsRoute
  '/dashboard': typeof DashboardRoute
  '/notifications': typeof NotificationsRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/transfer': typeof TransferRoute
  '/verification': typeof VerificationRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/beneficiaries': typeof AdminBeneficiariesRoute
  '/admin/cards': typeof AdminCardsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/transfers': typeof AdminTransfersRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/transfer-status/$id': typeof TransferStatusIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/cards': typeof CardsRoute
  '/dashboard': typeof DashboardRoute
  '/notifications': typeof NotificationsRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/transfer': typeof TransferRoute
  '/verification': typeof VerificationRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/beneficiaries': typeof AdminBeneficiariesRoute
  '/admin/cards': typeof AdminCardsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/transfers': typeof AdminTransfersRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/transfer-status/$id': typeof TransferStatusIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/cards'
    | '/dashboard'
    | '/notifications'
    | '/security'
    | '/settings'
    | '/transactions'
    | '/transfer'
    | '/verification'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/beneficiaries'
    | '/admin/cards'
    | '/admin/customers'
    | '/admin/kyc'
    | '/admin/notifications'
    | '/admin/security'
    | '/admin/transfers'
    | '/receipt/$id'
    | '/transfer-status/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/cards'
    | '/dashboard'
    | '/notifications'
    | '/security'
    | '/settings'
    | '/transactions'
    | '/transfer'
    | '/verification'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/beneficiaries'
    | '/admin/cards'
    | '/admin/customers'
    | '/admin/kyc'
    | '/admin/notifications'
    | '/admin/security'
    | '/admin/transfers'
    | '/receipt/$id'
    | '/transfer-status/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/cards'
    | '/dashboard'
    | '/notifications'
    | '/security'
    | '/settings'
    | '/transactions'
    | '/transfer'
    | '/verification'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/beneficiaries'
    | '/admin/cards'
    | '/admin/customers'
    | '/admin/kyc'
    | '/admin/notifications'
    | '/admin/security'
    | '/admin/transfers'
    | '/receipt/$id'
    | '/transfer-status/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  CardsRoute: typeof CardsRoute
  DashboardRoute: typeof DashboardRoute
  NotificationsRoute: typeof NotificationsRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  TransactionsRoute: typeof TransactionsRoute
  TransferRoute: typeof TransferRoute
  VerificationRoute: typeof VerificationRoute
  ReceiptIdRoute: typeof ReceiptIdRoute
  TransferStatusIdRoute: typeof TransferStatusIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/transfer-status/$id': {
      id: '/transfer-status/$id'
      path: '/transfer-status/$id'
      fullPath: '/transfer-status/$id'
      preLoaderRoute: typeof TransferStatusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/$id': {
      id: '/receipt/$id'
      path: '/receipt/$id'
      fullPath: '/receipt/$id'
      preLoaderRoute: typeof ReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transfers': {
      id: '/admin/transfers'
      path: '/transfers'
      fullPath: '/admin/transfers'
      preLoaderRoute: typeof AdminTransfersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cards': {
      id: '/admin/cards'
      path: '/cards'
      fullPath: '/admin/cards'
      preLoaderRoute: typeof AdminCardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/beneficiaries': {
      id: '/admin/beneficiaries'
      path: '/beneficiaries'
      fullPath: '/admin/beneficiaries'
      preLoaderRoute: typeof AdminBeneficiariesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBeneficiariesRoute: typeof AdminBeneficiariesRoute
  AdminCardsRoute: typeof AdminCardsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminKycRoute: typeof AdminKycRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminTransfersRoute: typeof AdminTransfersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBeneficiariesRoute: AdminBeneficiariesRoute,
  AdminCardsRoute: AdminCardsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminKycRoute: AdminKycRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminTransfersRoute: AdminTransfersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  CardsRoute: CardsRoute,
  DashboardRoute: DashboardRoute,
  NotificationsRoute: NotificationsRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  TransactionsRoute: TransactionsRoute,
  TransferRoute: TransferRoute,
  VerificationRoute: VerificationRoute,
  ReceiptIdRoute: ReceiptIdRoute,
  TransferStatusIdRoute: TransferStatusIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
